#!/usr/bin/env node
import { program } from 'commander'
import { Config } from './types'
import path from 'path'
import App from './classes/App'
import { cosmiconfigSync } from 'cosmiconfig'

const defaultConfig = {
  srcDir: '.sst',
  outDir: 'api-types',
}

program.option(
  '--srcDir <dir>',
  'The folder in which to look for constructs.json and functions.jsonl',
  defaultConfig.srcDir
)

program.option(
  '--outDir <dir>',
  'The folder in which to write the interface files generated by the program',
  defaultConfig.outDir
)

const fileOptions: Partial<Config> =
  cosmiconfigSync('sstApiTypes').search()?.config || {}

const commandLineOptions: Partial<Config> = program.parse().opts()

const config = { ...defaultConfig, ...fileOptions, ...commandLineOptions }

config.srcDir = path.join(process.cwd(), config.srcDir)
config.outDir = path.join(process.cwd(), config.outDir)

new App(config).generateTypes()
